language: perl
perl:
  - "5.30"
  - "5.26"
  - "5.22"
  - "5.16"
  - "5.14"
  - "5.10"
  - "5.8"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz
 - eval $(curl https://travis-perl.github.io/init) --auto

branches:
 except:
  - /appveyor/
